### ISSUE TITLE
DigiDoc4-client fails to build on newer Qt versions.

### ISSUE THREAD

**Issue by smirnov** [open-eid/DigiDoc4-Client#262]
Submodule for qtsingleapp included in the repo is from common @ 496a537 which lacks the commit to fix the build for Qt versions 5.11 and newer, which removed qt5_use_modules.

But even with manually porting over the fix, build of QDigiDoc4 fails with

```
BUILDSTDERR: /builddir/build/BUILD/DigiDoc4-Client-4.0.0/client/dialogs/Updater.cpp: In member function 'QPCSCReader::Result UpdaterPrivate::verifyPIN(const QString&, int) const':
BUILDSTDERR: /builddir/build/BUILD/DigiDoc4-Client-4.0.0/client/dialogs/Updater.cpp:214:30: error: expected type-specifier before 'QRegExpValidator'
BUILDSTDERR:    pinInput->setValidator(new QRegExpValidator(regexp, pinInput));
BUILDSTDERR:                               ^~~~~~~~~~~~~~~~
BUILDSTDERR: make[2]: *** [client/CMakeFiles/qdigidoc4.dir/build.make:725: client/CMakeFiles/qdigidoc4.dir/dialogs/Updater.cpp.o] Error 1
make[2]: Leaving directory '/builddir/build/BUILD/DigiDoc4-Client-4.0.0'
BUILDSTDERR: make[2]: *** Waiting for unfinished jobs....
make[2]: Entering directory '/builddir/build/BUILD/DigiDoc4-Client-4.0.0'
[ 77%] Building CXX object client/CMakeFiles/qdigidoc4.dir/dialogs/PinUnblock.cpp.o
cd /builddir/build/BUILD/DigiDoc4-Client-4.0.0/client && /usr/bin/c++  -DAPP=\"qdigidoc4\" -DBUILD_DATE=\"14.06.2018\" -DBUILD_VER=0 -DDATADIR=\"/usr/share\" -DMAJOR_VER=4 -DMINOR_VER=0 -DPKCS11_MODULE=\"opensc-pkcs11.so\" -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_SVG_LIB -DQT_WIDGETS_LIB -DRELEASE_VER=0 -DVER_SUFFIX=\"\" -I/builddir/build/BUILD/DigiDoc4-Client-4.0.0/client -I/builddir/build/BUILD/DigiDoc4-Client-4.0.0/client/qdigidoc4_autogen/include -I/builddir/build/BUILD/DigiDoc4-Client-4.0.0 -I/builddir/build/BUILD/DigiDoc4-Client-4.0.0/common -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtSvg -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtCore -isystem /usr/lib64/qt5/./mkspecs/linux-g++ -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtPrintSupport  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fvisibility=hidden -fvisibility-inlines-hidden   -fPIC -std=gnu++11 -o CMakeFiles/qdigidoc4.dir/dialogs/PinUnblock.cpp.o -c /builddir/build/BUILD/DigiDoc4-Client-4.0.0/client/dialogs/PinUnblock.cpp
BUILDSTDERR: /builddir/build/BUILD/DigiDoc4-Client-4.0.0/client/dialogs/PinUnblock.cpp: In member function 'void PinUnblock::init(PinUnblock::WorkMode, QSmartCardData::PinType, short int)':
BUILDSTDERR: /builddir/build/BUILD/DigiDoc4-Client-4.0.0/client/dialogs/PinUnblock.cpp:108:29: error: expected type-specifier before 'QRegExpValidator'
BUILDSTDERR:   ui->puk->setValidator( new QRegExpValidator( regexpFirstCode, ui->puk ) );
BUILDSTDERR:                              ^~~~~~~~~~~~~~~~
BUILDSTDERR: /builddir/build/BUILD/DigiDoc4-Client-4.0.0/client/dialogs/PinUnblock.cpp:109:29: error: expected type-specifier before 'QRegExpValidator'
BUILDSTDERR:   ui->pin->setValidator( new QRegExpValidator( regexpFirstCode, ui->pin ) );
BUILDSTDERR:                              ^~~~~~~~~~~~~~~~
BUILDSTDERR: /builddir/build/BUILD/DigiDoc4-Client-4.0.0/client/dialogs/PinUnblock.cpp:110:32: error: expected type-specifier before 'QRegExpValidator'
BUILDSTDERR:   ui->repeat->setValidator( new QRegExpValidator( regexpFirstCode, ui->repeat ) );
BUILDSTDERR:                                 ^~~~~~~~~~~~~~~~
BUILDSTDERR: make[2]: *** [client/CMakeFiles/qdigidoc4.dir/build.make:738: client/CMakeFiles/qdigidoc4.dir/dialogs/PinUnblock.cpp.o] Error 1
make[2]: Leaving directory '/builddir/build/BUILD/DigiDoc4-Client-4.0.0'
BUILDSTDERR: make[1]: *** [CMakeFiles/Makefile2:381: client/CMakeFiles/qdigidoc4.dir/all] Error 2
BUILDSTDERR: make: *** [Makefile:133: all] Error 2
BUILDSTDERR: error: Bad exit status from /var/tmp/rpm-tmp.8nlQ8e (%build)
RPM build errors:
BUILDSTDERR:     Bad exit status from /var/tmp/rpm-tmp.8nlQ8e (%build)
Child return code was: 1
EXCEPTION: [Error()]
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/mockbuild/trace_decorator.py", line 96, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.6/site-packages/mockbuild/util.py", line 628, in do
    raise exception.Error("Command failed: \n # %s\n%s" % (command, output), child.returncode)
mockbuild.exception.Error: Command failed: 
 # /usr/bin/systemd-nspawn -q -M 2fdcf7363d29419ebbe9a40a5ca2af4d -D /var/lib/mock/766873-fedora-rawhide-x86_64-1529009784.571452/root -a --setenv=TERM=vt100 --setenv=SHELL=/bin/bash --setenv=HOME=/builddir --setenv=HOSTNAME=mock --setenv=PATH=/usr/bin:/bin:/usr/sbin:/sbin --setenv=PROMPT_COMMAND=printf "\033]0;<mock-chroot>\007" --setenv=PS1=<mock-chroot> \s-\v\$  --setenv=LANG=en_US.UTF-8 -u mockbuild bash --login -c /usr/bin/rpmbuild -bb --target x86_64 --nodeps /builddir/build/SPECS/digidoc4.spec
```

**Comment by urmet** [comment]
Aha. I was almost ready to do these include fixes myself but was too busy for the last few days :)
